In [ ]:
# Resource : https://www.w3schools.com/python/scipy/scipy_constants.php

In [2]:
from scipy import cluster

In [3]:
from scipy import constants

In [4]:
print(constants.litre)

0.001


In [5]:
print(constants.pi)

3.141592653589793


In [6]:
# A list of all units under the constants module can be seen using the dir() function.

print(dir(constants))

['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_obsolete_constants', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_ratio', 'grain', 'gram', 'gravitational_con

In [8]:
# Metric (SI) Prefixes: Return the specified unit in meter (e.g. centi returns 0.01)

print(constants.kilo)



1000.0


In [10]:
# Binary Prefixes: Return the specified unit in bytes (e.g. kibi returns 1024)
print(constants.gibi)

#Mass: Return the specified unit in kg (e.g. gram returns 0.001)
print(constants.metric_ton)
print(constants.gram)

# Angle: Return the specified unit in radians (e.g. degree returns 0.017453292519943295)
print(constants.degree)

# Time - Seconds
# Length - Meters
# Pressure - Pascals
# Area - Square meters
# Volume - cubic meters (e.g. liter returns 0.001)
# Speed - meters per second (e.g. speed_of_sound returns 340.5)

# Temp -  Kelvin (e.g. zero_Celsius returns 273.15)
print(constants.degree_Fahrenheit) 

# Energy - joules (e.g. calorie returns 4.184)
# Power - (e.g. horsepower returns 745.6998715822701)
print(constants.hp)

# Force -  newton (e.g. kilogram_force returns 9.80665)

print(constants.dyn)             #1e-05
print(constants.dyne)            #1e-05
print(constants.lbf)             #4.4482216152605
print(constants.pound_force)     #4.4482216152605
print(constants.kgf)             #9.80665
print(constants.kilogram_force)  #9.80665


1073741824
1000.0
0.001
0.017453292519943295
0.5555555555555556
745.6998715822701
1e-05
1e-05
4.4482216152605
4.4482216152605
9.80665
9.80665


In [11]:
# Optimizers - Set of procedures defined in SciPy that either find the minimum value of function,or the root of an equation.
# Essentially, all of the algorithms in Machine Learning are nothing more than a complex equation
# that needs to be minimized with the help of given data.
# Roots of an Equation - NumPy is capable of finding roots for polynomials and linear equations,
# but it can not find roots for non linear equations, like this one:x + cos(x)

#-----------------------------------------------------------------------------------------------------------------------------

# optimize.root function -> 2 arguments required
# fun - a function representing an equation.
# x0 - an initial guess for the root.

# Question -> Find root of the equation x + cos(x):
from scipy.optimize import root
from math import cos 

def eqn(x):
    return x + cos(x)

myroot = root(eqn,0)
print(myroot.x)
print(myroot)



[-0.73908513]
    fjac: array([[-1.]])
     fun: array([0.])
 message: 'The solution converged.'
    nfev: 9
     qtf: array([-2.66786593e-13])
       r: array([-1.67361202])
  status: 1
 success: True
       x: array([-0.73908513])


In [12]:
# A function, in this context, represents a curve, curves have high points and low points.
# High points - maxima.
# Low points - minima.
# The highest point in the whole curve - global maxima; rest - local maxima.
# The lowest point in whole curve is called global minima; rest - local minima.

#-------------------------------------------------------------------------------------------------------------------------------

# The minimize() function takes the following arguments:
# fun - a function representing an equation.
# x0 - an initial guess for the root.
# method - name of the method to use. Legal values:'CG''BFGS''Newton-CG''L-BFGS-B''TNC''COBYLA''SLSQP'
#callback - function called after each iteration of optimization.
# options - a dictionary defining extra params: { "disp": boolean - print detailed description "gtol": number - the tolerance of the error}

# Example -> Minimize the function x^2 + x + 2 with BFGS:

from scipy.optimize import minimize

def eqn(x):
  return x**2 + x + 2

mymin = minimize(eqn, 0, method='BFGS')

print(mymin)

      fun: 1.75
 hess_inv: array([[0.50000001]])
      jac: array([0.])
  message: 'Optimization terminated successfully.'
     nfev: 8
      nit: 2
     njev: 4
   status: 0
  success: True
        x: array([-0.50000001])


In [14]:
from scipy.optimize import minimize

def eqn(x):
    return x**2 + x + 2
mymin = minimize(eqn, 0, method='TNC')
print(mymin)

     fun: array([1.75])
     jac: array([2.22044605e-08])
 message: 'Local minimum reached (|pg| ~= 0)'
    nfev: 8
     nit: 1
  status: 0
 success: True
       x: array([-0.5])


In [15]:
# Interpolation 

from scipy.interpolate import interp1d
import numpy as np

xs = np.arange(10)
ys = 2*xs + 1

interp_func = interp1d(xs, ys)

newarr = interp_func(np.arange(2.1, 3, 0.1))

print(newarr)

[5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8]


In [16]:
# Matlab Default bool - False

# Export - savemat Import - loadmat
from scipy import io
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9,])

# Export:
io.savemat('arr.mat', {"vec": arr})

# Import:
mydata = io.loadmat('arr.mat')

print(mydata)


{'__header__': b'MATLAB 5.0 MAT-file Platform: nt, Created on: Mon Dec 13 06:23:06 2021', '__version__': '1.0', '__globals__': [], 'vec': array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])}


In [17]:
# "vec" to display only the array from the matlab data
print(mydata['vec'])

[[0 1 2 3 4 5 6 7 8 9]]


In [18]:
# array originally was 1D, but on extraction it has increased one dimension.

#In order to resolve this we can pass an additional argument squeeze_me=True:
# Import:
mydata = io.loadmat('arr.mat', squeeze_me=True)

print(mydata['vec'])

[0 1 2 3 4 5 6 7 8 9]
